### ISSUE TITLE
ETQ manager, je souhaite pouvoir mettre à jour les données des bénéficiaires par import.

### ISSUE THREAD

**Issue by bChiquet** [SocialGouv/carnet-de-bord#1038]
**Problème :**
Quand j'importe un fichier de bénéficiaires actuellement, les bénéficiaires déjà importés ne sont pas ré-importés, même quand leurs données ont changé.
Pourtant, certains champs, comme l'état du droit, sont actualisés régulièrement.
J'aimerais avoir un moyen de mettre à jour ces champs en masse dans Carnet de Bord.

**Proposition :**
Quand j'importe un bénéficiaire déjà importé dans Carnet de Bord, les champs **variables** (par exemple, "état du droit") sont mis à jour dans Carnet de Bord selon la valeur fournie dans l'import.
Si je modifie un champ **non-variable** (par exemple, "date de naissance"), le champ n'est pas mis à jour.
Le résumé de l'opération d'import m'indique le nombre de bénéficiaires déjà existants updatés.

**Points en suspens :**
* La liste des champs **variables** et **non-variables**.
* Si un bénéficiaire a un champ **variable** et un champ **non-variable** modifiés, faut-il mettre à jour les champs **variables** ou bloquer toute l'update du bénéficiaire ?

**Comment by lkouad** [comment]
@bChiquet Pour moi la question "Si un bénéficiaire a un champ variable et un champ non-variable modifiés, faut-il mettre à jour les champs variables ou bloquer toute l'update du bénéficiaire ?" Pour moi oui, et l'utilisateur remonte les info au support si besoin
Dans l'ideal le résultat de l'importation est  montré par le systeme via la liste des bénéficiaires créés, les exceptions sont ignorées et le systeme indique par mail les imports ignorés avec le motif (je tente lol )

**Comment by lkouad** [comment]
Comme ça l'utilisateur pourras revenir vers le support en justifiant pourquoi il y a une modification du champs non-variable (et nous apprendrons mieux sur les exceptions ;) )

**Comment by bChiquet** [comment]
> Pour moi oui

J'entends "oui, on ne modifie rien", ou bien "oui, on modifie seulement les champs variables" ?

> Dans l'ideal le résultat de l'importation est montré par le systeme via la liste des bénéficiaires créés

Si les imports se pérennisent (💀) il faudrait qu'on fasse du résultat d'import un objet first class du système, qui peut être consulté et partagé. Mais on pourra voir ça dans un second temps :)

**Comment by lionelB** [comment]
close by #1125
