### ISSUE TITLE
[Import des données PE] Doublons des profils pro importés via PE et Importé via manager

### ISSUE THREAD

**Issue by lkouad** [SocialGouv/carnet-de-bord#1080]
## :wrench: Problème / Contexte

Nous importons les pro avec une adresse mail en " .net"  (C'est une demande de PE), sauf que les pro utilisent leur point FR et sont donc enregistrés dans les contacts avec les autre département en " .fr" Résultat: J'ai une madameXXX en .fr et une madamexxxx en.net 

Et avec des structures différentes..

Pour les référents PE, nous souhaitons qu'ils ne soient référencés qu'avec leur adresse en .net dans la base.

## :cake: Comportement attendu

Chercher les doublons « PE » dans la base. C'est à dire un professionnel qui est enregistré deux fois, une fois avec son adresse en .fr et l'autre fois avec son adresse en .net.

Pour ce faire, il faudra chercher si une adresse équivalente à celle de PE en `.net` est déjà présente en base. Par exemple, `05prenom.nom@pole-emploi.net` correspondrait à `prenom.nom@pole-emploi.fr` dans CDB.

Si c'est le cas, il faudra fusionner les informations du pro en .fr sur le pro en .net et « supprimer » (ou rendre inactif) le pro en .fr.
Ne pas aussi oublier de supprimer ou rendre inactif les structures qui ont été créées et qui ne contenaient que des .fr qui ont été fusionnés avec les .net.

**Comment by vjousse** [comment]
État actuel des réflexions sur Notion https://www.notion.so/2022-08-29-PE-Doublons-pro-p-le-emploi-a84d9104bdf941238ffb96ebc5a0c4b4
