### ISSUE TITLE
Alerter sur les erreurs des scripts PE

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/carnet-de-bord#1105]
##  :ice_cube:  Problème

Actuellement, l'équipe dev n'est pas au courant lorsque les scripts PE (pe-fetch / pe-parse) ne s'exécute pas correctement. Récemment, sentry a été branché sur le script pe-parse mais cela n'est pas encore suffisant car l’équipe dev doit aller se connecter sur sentry pour avoir l'information.

## :icecream: Solution
Créer un canal dédié sur mattermost pour recevoir des notifications concernant les problèmes d’exécution des différents  scripts / jobs.

**Comment by vjousse** [comment]
Est-ce qu'on ne peut pas configurer simplement Sentry pour qu'il envoie des emails dans ce cas là ? Peut-être à doubler avec Mattermost en effet.

**Comment by HEYGUL** [comment]
A voir si on peut utiliser ce plugin Sentry qui semble répondre au besoin : https://github.com/NDrive/sentry-mattermost

**Comment by vjousse** [comment]
J'ai mes en place l'alerting par email
