### ISSUE TITLE
fichier d'import des structures

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/carnet-de-bord#1119]
## :bug: Problème

Actuellement, lorsqu'on insère des structures, il n'y a pas de pré-traitement (trim) ni d'index qui permette de limiter les duplications de structure.

## :cake: Solution

Créer un index / une contrainte qui permette d’empêcher la création d'une structure avec le même nom quelque soit la casse

**Comment by lkouad** [comment]
@lionelB j'ai pas compris? Si tu as une structure du même nom mais pas la même adresse?

**Comment by lionelB** [comment]
non on avait des structures avec le même nom (mais avec un espace, ou écrite en minuscule) sur le même territoire
