### ISSUE TITLE
Gérer les adresses en .fr dans le script d'import

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/carnet-de-bord#1130]
## :cloud_with_rain:  Problème 
Le script d'import des données pole-emploi crée un compte pour les référent PE des brsa qu'on trouve dans le fichier.
Dans certains cas, le pro existe déja mais avec une adresse en `.fr` ce qui ne permet pas au script de retrouver la personne.

## :cake:  Solution
Avant de créer un pro avec son adresse .net, il faudrait préalablement vérifier que le même pro n'existe pas déjà avec une adresse en `.fr`
Si c'est le cas, on peut assigner le brsa au pro en .fr et modifier son mail en `.net` (et peut être envoyé un mail si celui si c'est déjà connecté)

**Comment by vjousse** [comment]
Closed by #1181
