### ISSUE TITLE
le bouton déconnexion disparait si l'écran est trop petit

### ISSUE THREAD

**Issue by tglatt** [SocialGouv/carnet-de-bord#159]
<img width="986" alt="Capture d’écran 2021-09-08 à 19 47 09" src="https://user-images.githubusercontent.com/47273014/132559048-dd773d3c-b4ae-4b38-bd05-f1d5725d066d.png">

**Comment by Augustin82** [comment]
Plus largement, le site est pas mobile-friendly pour l'instant. À prioriser.
