### ISSUE TITLE
Suppression des usagers d'un déploiement (40- Landes)

### ISSUE THREAD

**Issue by oblab** [SocialGouv/carnet-de-bord#1763]
### :crying_cat_face:  Comportement observé

Le déploiement des Landes (5699e0b2-4e43-4ded-a9c0-235bca0f0090) contient actuellement 2 bénéficiaires qui sont de faux profils  : 

- DUPONT Marie (4c9626f6-3270-440e-89a9-959caa977d2
- fondue charlot (562d1c5d-3231-46fd-ac84-b98cc00dc97a)

Le département souhaitant débuter une expé, il faut procéder à un nettoyage.

### :dart: Comportement attendu

Supprimer tous les bénéficiaires (au nombre de deux) du déploiement

**Comment by HEYGUL** [comment]
Fait.
