### ISSUE TITLE
Intégrer les libellé ROM

### ISSUE THREAD

**Issue by tglatt** [SocialGouv/carnet-de-bord#180]
Dans la informations socio pro, le métier est demandé. La liste des métier est ci-dessous:

Libellé ROME V3 https://www.data.gouv.fr/fr/datasets/r/a4031fcf-0ded-47df-9d88-870c06c8321e

Il fait développer un composant pour permettre dans leur sélection et l'utiliser dans `ProBeneficiarySocioProUpdate.svelte`

**Comment by Augustin82** [comment]
Résolu par https://github.com/SocialGouv/carnet-de-bord/pull/192
