### ISSUE TITLE
Création de carnets depuis rdv-i

### ISSUE THREAD

**Issue by oblab** [SocialGouv/carnet-de-bord#1927]
### :footprints: Étapes pour reproduire
Une pro de la Creuse a créé des carnets depuis rdv-i, sans difficultés particulières, sauf pour 4 usagers

### :crying_cat_face:  Comportement observé
Erreur 400 obtenue dans RDV-i au moment de la tentative de création des carnets pour les 4 usagers listés ici : 
[https://mattermost.incubateur.net/betagouv/pl/5h46dkeu63dq8dfpad8k5yuf9c](https://mattermost.incubateur.net/betagouv/pl/5h46dkeu63dq8dfpad8k5yuf9c)
### :dart: Comportement attendu

les carnets devraient se créer normalement, étant donné que la pro a les bons droits et que les usagers n'exisent pas encore dans CDB

### :recycle: Environnement

Environnement (dev, prod...) : prod

**Comment by chdechamps** [comment]
Doublon dans le numéro SI sur RDV-i. 
Solution définitive : passage du N° SI au NIR pour éviter les pbs avec IODAS (prérecquis : importer les NIR de tous les bénéficiaires préalablement). 
Solution temporaire : créer a la main les carnets dans cette situation. Information complémentaire nécessaire concernant ces bénéficiaires (minima NIR + date de naissance)
