### ISSUE TITLE
Professionnel > Page Bénéficiaire > Situation socioprofessionnel > Mise à jour> Emploi recherché

### ISSUE THREAD

**Issue by lkouad** [SocialGouv/carnet-de-bord#218]
Ralentissement de la recherche :Je ne sais pas si c'est moi mais ça bug, ou ralentie
![image](https://user-images.githubusercontent.com/83343517/134239462-b9a6e55d-705d-4dac-af9e-d3b70b40ce78.png)

**Comment by tglatt** [comment]
il faut attendre au moins 3 lettre avant de lancer la recherche.
