### ISSUE TITLE
Professionnel > Page Bénéficiaire > Groupe de suivi > Ajouter un accompagnateur> Inviter un accompagnateur

### ISSUE THREAD

**Issue by lkouad** [SocialGouv/carnet-de-bord#219]
On ne comprend l'information "Identifiant" c'est quoi?
![image](https://user-images.githubusercontent.com/83343517/134240082-ae76e32f-d316-4067-ac3b-347c09756a40.png)

**Comment by tglatt** [comment]
masquer l'identifiant dans le cas d'une invitation

**Comment by ronanjames** [comment]
"Identifiant" correspond surement au champ Identifiant Pole emploi pour l'inscription d'un bénéficiaire, effectivement pas pertinent dans cette page.

**Comment by Augustin82** [comment]
Il s'agit en fait de l'identifiant de connexion de l'accompagnateur. Après discussion avec @tglatt et @lionelB, on a décidé de :
- ne plus permettre aux gens de choisir leur identifiant ;
- le générer automatiquement ;
- et donc, l'enlever des formulaires.

**Comment by lionelB** [comment]
closed by #247
