### ISSUE TITLE
Professionnel > Page Bénéficiaire > Groupe de suivi > Ajouter un accompagnateur> Recherche

### ISSUE THREAD

**Issue by lkouad** [SocialGouv/carnet-de-bord#220]
La fonction recherche ne marche pas j'ai testé avec les structures, les noms (teste fait avec ceux du groupe de suivi...)
![image](https://user-images.githubusercontent.com/83343517/134241087-12e67652-9945-4c05-8806-ea704b8be00b.png)

**Comment by tglatt** [comment]
vérifier qu'on recherche par nom de structure

**Comment by tglatt** [comment]
il n'y avait plus d'accompagnateur à rajouter. Mais sinon la recherche fonctionne
