### ISSUE TITLE
Professionnel > Page Bénéficiaire > Axe de travail > Type de contrat> Mise à jour champ aucun

### ISSUE THREAD

**Issue by lkouad** [SocialGouv/carnet-de-bord#223]
Quand "aucun" le champ de la date précédente reste
![image](https://user-images.githubusercontent.com/83343517/134242757-3262c748-212f-4579-8df8-6f124ca51696.png)

**Comment by tglatt** [comment]
- problème de mise à jour
- si on coche aucun, la date de signature doit être vidée et bloquer
