### ISSUE TITLE
Professionnel > Page Bénéficiaire > Axe de travail > Ajouter un axe de travail> Lien Theme et liste Objectif

### ISSUE THREAD

**Issue by lkouad** [SocialGouv/carnet-de-bord#224]
La liste d'objectifs n'est pas liée Thème (risque d'erreur)
![image](https://user-images.githubusercontent.com/83343517/134243920-2468b033-c9ae-4daf-8094-df8757a8f8e5.png)

**Comment by tglatt** [comment]
Ces 2 informations sont déjà liées. Ce lien est configurable est base de données
