### ISSUE TITLE
Professionnel > Page Bénéficiaire > Axe de travail > Une action> ajout action sans structure ko

### ISSUE THREAD

**Issue by lkouad** [SocialGouv/carnet-de-bord#226]
Il faut pouvoir ajouter une action sans structure et venir ajouter la structure plus tard
![image](https://user-images.githubusercontent.com/83343517/134245088-0bba42bb-4b32-4397-b3cf-ff3842442ed2.png)

**Comment by tglatt** [comment]
see https://github.com/SocialGouv/carnet-de-bord/issues/225
