### ISSUE TITLE
Professionnel > Page Bénéficiaire > Axe de travail > Ajouter un axe de travail>ajouter un objectif

### ISSUE THREAD

**Issue by lkouad** [SocialGouv/carnet-de-bord#228]
Lors de la création d'un axe de travail "logement" si j'ajoute l'objectif 'se maintenir dans le logement..." idem pour "recherche de logement" ils n'apparaissent pas idem pour les autres Axes
![image](https://user-images.githubusercontent.com/83343517/134246775-64678f42-325f-4a32-92c2-02a3c4a7eb75.png)

**Comment by lkouad** [comment]
En faite c'est bon c'est un ralentissement du coup:
![image](https://user-images.githubusercontent.com/83343517/134247243-9aa205fb-cd68-49fb-a0e4-4db9811e6c6b.png)

**Comment by lkouad** [comment]
Je propose que sur un axe l'utilisateur ne devrait pas pouvoir soumettre un objectif deux fois

**Comment by tglatt** [comment]
J'ai l'impression que le refresh ne se fait pas à la création du premier objectif
