### ISSUE TITLE
 Professionnel > Page Accueil > Derniers profils modifiés>pas de Maj

### ISSUE THREAD

**Issue by lkouad** [SocialGouv/carnet-de-bord#229]
Modification du profil Dinum mais pas de MaJ dans Derniers profils modifiés
![image](https://user-images.githubusercontent.com/83343517/134250160-ef4c385a-01b6-47f6-ae1b-db7ab41e3d62.png)

**Comment by tglatt** [comment]
Normal, on remonte uniquement les dossiers modifiés par les autres accompagnateurs.

C'est ce qui était prévu avec Pauline
