### ISSUE TITLE
Supprimer le contenu d'un champ existant

### ISSUE THREAD

**Issue by lkouad** [SocialGouv/carnet-de-bord#232]
La suppression d'une donnée sans remplacement pour tout enregistrement  doit demander une confirmation.

**Comment by lionelB** [comment]
hello @lkouad, est ce que tu peux preciser le contexte, avec un exemple ça serait top

**Comment by lkouad** [comment]
J'ai supprimé le nom et le prénom de la personne 
![image](https://user-images.githubusercontent.com/83343517/134486434-8bd5ccea-4500-4049-9629-7b7208792088.png)

**Comment by lionelB** [comment]
done in #442
