### ISSUE TITLE
Champ Obligatoire

### ISSUE THREAD

**Issue by lkouad** [SocialGouv/carnet-de-bord#233]
- [ ] Tous les champs obligatoires doivent être validés
- [x] Tous les champs obligatoires doivent être signalés par un astérisque (*)

**Comment by Augustin82** [comment]
@lkouad tu peux nous communiquer pour chaque formulaire la liste des champs obligatoires et leur condition de validité ?

**Comment by lionelB** [comment]
done in #442 #460 #464
