### ISSUE TITLE
Formatage Champ Adresse mail

### ISSUE THREAD

**Issue by lkouad** [SocialGouv/carnet-de-bord#234]
Il manque le formatage "nom de domaine"

**Comment by lionelB** [comment]
Hello, est ce que tu peux un peu de contexte et expliciter ce que tu attends ?  merci.

**Comment by lkouad** [comment]
L'enregistrement de l'adresse mail doit être faite avec le nom de domaine
![image](https://user-images.githubusercontent.com/83343517/134485865-b79c994c-cdcc-46a4-b216-a9aa4d46a652.png)

**Comment by lkouad** [comment]
Soit on passe les champs en Obligatoire soit on demande une confirmation avant enregistrement

**Comment by lionelB** [comment]
pour info ;) https://en.wikipedia.org/wiki/Email_address#Examples  
on va travailler sur la validation des champs

**Comment by lkouad** [comment]
Ouais mais tu sais tu devrais te méfier wikipedia c'est pas fiable, je plaisante ;) ;)

**Comment by lionelB** [comment]
done in #464, #460, #442, #484
