### ISSUE TITLE
Toutes les valeurs numériques doivent être correctement formatées.

### ISSUE THREAD

**Issue by lkouad** [SocialGouv/carnet-de-bord#236]
Téléphone
Code postal

**Comment by Augustin82** [comment]
Même question que pour #237

**Comment by lkouad** [comment]
Les champs Code postal et téléphone doivent imposer des entrées numérique uniquement
![image](https://user-images.githubusercontent.com/83343517/134491619-91443549-d1f9-4189-839f-de8dbf0ff98e.png)

**Comment by lionelB** [comment]
done in #464, #460, #442, #484
