### ISSUE TITLE
Professionnel > Page Bénéficiaire > Informations socio-professionnelle -> Diplomes

### ISSUE THREAD

**Issue by ronanjames** [SocialGouv/carnet-de-bord#246]
La nomenclature des niveaux de formation a changé en 2019. 
Il faudrait changer la liste du champs "Diplôme" :
Niveau 3 = CAP, BEP
Niveau 4 =  Baccalauréat
Niveau 5 = DEUG, BTS, DUT, DEUST
Niveau 6 = Licence et Maître, master 1
Niveau 7 = Master et diplôme d'études approfondies
Niveau 8 = Doctorat

source : https://www.service-public.fr/particuliers/vosdroits/F199

**Comment by ronanjames** [comment]
![Capture d’écran 2021-09-23 à 13 35 47](https://user-images.githubusercontent.com/10141370/134501576-c29eb4ff-c68c-42de-92e8-00be5caab891.png)

**Comment by Augustin82** [comment]
@ronanjames il n'y a plus de niveau 1 et 2, alors ? Chez nous il y avait "formation courte" et "Formation courte max 1 mois" et "Pas de formation / Pas de diplôme", on zappe ?

**Comment by ronanjames** [comment]
Bien vu @Augustin82, la description propre de la nomenclature commence au Niveau 3. 
Typiquement, c'est une question que je préciserais avec un retour utilisateur. 
Merci beaucoup pour les modifs 🙌

**Comment by Augustin82** [comment]
@ronanjames on avance comme ça alors ? Je ferme l'issue ?

**Comment by ronanjames** [comment]
Yep, on peut fermer pour l’instant
Merci
