### ISSUE TITLE
Professionnel > Page Bénéficiaire > Axes de travail > Fiche d'un axe de travail

### ISSUE THREAD

**Issue by ronanjames** [SocialGouv/carnet-de-bord#248]
Dans la fiche d'un axe de travail (ex : Difficultés administratives, Logement, Emploi), le tableau des objectifs arrive tout en bas de la page, alors que c'est une information avec plus éléments importants. 
Est-ce qu'il serait possible de mettre la ligne "Objectif" avant la ligne "Créé par / Structures sollicitées" ? 
Ca permettrait d'avoir "Situation", puis "Objectifs" juste en-dessous (plutôt logique dans le sens de lecture de l'info)
Cout de dev : très faible (dixit team Dev) 
Gain en visibilité de l'info : ++

**Comment by ronanjames** [comment]
![Capture d’écran 2021-09-23 à 15 33 35](https://user-images.githubusercontent.com/10141370/134518329-447a9027-bebb-4beb-9b1a-8efd7afc944c.png)

**Comment by Augustin82** [comment]
À discuter ensemble avec Jonathan.

**Comment by ronanjames** [comment]
On a documenté la carte avec Jo et Lio en début d'aprem, mais bien-sûr ;)

**Comment by Augustin82** [comment]
Pas de problème alors !

**Comment by ronanjames** [comment]
Youpi, merci :D
