### ISSUE TITLE
Général > Champs de saisie

### ISSUE THREAD

**Issue by JonathanetRaimond** [SocialGouv/carnet-de-bord#258]
- [x] Ajuster la longueur des champs de saisie cf Design
- [x] Placer les champs de saisie cf Design (ex: le code postal et la ville sont sur la même ligne)
- [x] L’espace entre le champ de saisie et son label doit être de 8px
Remplacer « Adresse de courriel » par « Email »

**Comment by lionelB** [comment]
Adresse de courriel est remplacé par courriel plutot qu'email
