### ISSUE TITLE
Accueil (à validé)

### ISSUE THREAD

**Issue by JonathanetRaimond** [SocialGouv/carnet-de-bord#259]
• Sous le titre « Derniers profils consultés » afficher 3 ou 4 profils
• Sous le titre « Derniers profils modifiés » afficher 2 ou 3 profils
![1_Accueil](https://user-images.githubusercontent.com/90344173/134594754-57cb261c-9f68-4f2a-8834-a1f8fbbe6f9e.png)

**Comment by Augustin82** [comment]
@JonathanetRaimond désolé, je n'ai pas compris ce que tu voulais dire précisément. Tu veux bien mettre combien de cartes il faut afficher dans chaque section, ainsi que s'il faut afficher une carte spéciale ("voir tous les profils" par exemple), ce qu'on affiche quand il y en a pile le nombre à afficher, ou moins, etc.

Merci !

**Comment by JonathanetRaimond** [comment]
Pour la démo ce serait mieux d'avoir un peu de contenu sur la page d'accueil. 
On peut afficher :
Derniers profils consultés > 4 cartes
Derniers profils modifiés > 2 cartes
Pour plus tard…
Si il y a plus de 4 profils dans "Derniers profils consultés" ou "Derniers profils modifiés" on remplace la dernière cartes "profil" par une carte "spéciale" (voir tou…)

**Comment by Augustin82** [comment]
OK, donc tu demandes deux choses séparées :
- gérer l'UI de la page d'accueil (je peux le faire)
- ajouter des données spécifiquement pour la démo (@tglatt @lionelB)

La carte spécial "Voir tous les profils" elle amène où ? Sur la page "Annuaire de mes bénéficiaires" ?

**Comment by JonathanetRaimond** [comment]
Oui

**Comment by lionelB** [comment]
plus d'actualité
