### ISSUE TITLE
Mon compte > Nouvel écran (à validé)

### ISSUE THREAD

**Issue by JonathanetRaimond** [SocialGouv/carnet-de-bord#260]
Faire deux écrans pour mon compte (visualisation + édition)
![6_Mon_compte_1](https://user-images.githubusercontent.com/90344173/135065754-d9defaa0-c5a9-4cdf-ae8b-0d0c940be0cc.png)

https://app.zeplin.io/project/60f4be47ce378d15260bbe8f/screen/6152e27e135b66127f0cff74

![6_Mon_compte_2](https://user-images.githubusercontent.com/90344173/135065786-2c6ac98b-815f-4e51-90eb-e16a6622ddde.png)

https://app.zeplin.io/project/60f4be47ce378d15260bbe8f/screen/6152e27d2ed572164ac6d5a8

**Comment by lionelB** [comment]
Est ce que tu peux détaillé ? si possible mettre une capture d'écran

**Comment by Augustin82** [comment]
=> Avoir un écran d'affichage simple, et un bouton éditer qui ouvre le volet latéral.

**Comment by Augustin82** [comment]
@JonathanetRaimond on a pas d'UI dans Zeplin pour ça : tu préfères que j'en improvise une ou qu'on laisse ça de côté pour l'instant ?

**Comment by JonathanetRaimond** [comment]
Je m'en occupe, je te préviens dés que c'est sur Zeplin

**Comment by Augustin82** [comment]
https://app.zeplin.io/project/60f4be47ce378d15260bbe8f/screen/6152e27e135b66127f0cff74

**Comment by Augustin82** [comment]
Résolu par #315
