### ISSUE TITLE
Annuaire des bénéficiaires > Filtre (à validé)

### ISSUE THREAD

**Issue by JonathanetRaimond** [SocialGouv/carnet-de-bord#261]
Le filtre « Profils consultés » doit avoir une option sélectionnée par défaut ex: dans les 3 derniers mois
Question : Doit-on ajouter une option « Tous les profils » et la mettre par défaut ?
![2_Annuaire_beneficiaire_1](https://user-images.githubusercontent.com/90344173/134594636-e270a5ba-f527-4084-9019-54580606c134.png)

**Comment by Augustin82** [comment]
Doit-on ajouter une option « Tous les profils » et la mettre par défaut ?
=> Je pense que non.

**Comment by Augustin82** [comment]
Résolu par https://github.com/SocialGouv/carnet-de-bord/commit/8943c332da8abe42a6e87b188970e1a75de65db9
