### ISSUE TITLE
Ajouter un bénéficiaire > Passer en mode wizzard (maquettes)

### ISSUE THREAD

**Issue by JonathanetRaimond** [SocialGouv/carnet-de-bord#262]
- [x] Ajouter un espace insécable avant le point d’interrogation dans la phrase sous le titre.  #250
- [x] Le btn « Valider » ne doit pas être afficher dés la première étape. Il doit apparaître à la dernière étape pour valider le formulaire et il doit être actif pour voir les messages d’erreurs.
- [x] Ajouter les titres des étapes pour identifiant CAF + Pôle emploi
	1. Rechercher un profil avec l’identifiant Pôle emploi
	2. Sélectionner un profil
	3. Valider les information du profil 

![3_Ajouter_beneficiaire_2 1 3](https://user-images.githubusercontent.com/90344173/134594553-17197e59-34de-43b4-9472-3dc9cd0086f8.png)

**Comment by Augustin82** [comment]
Voir maquettes (3_Ajouter_bénéficiaire) :
https://app.zeplin.io/project/60f4be47ce378d15260bbe8f/screen/6149f62db2374ab4b3c93038

**Comment by lionelB** [comment]
done in  #289
