### ISSUE TITLE
Fiche bénéficiaire > Informations personnelles > Formulaire de mise à jour 

### ISSUE THREAD

**Issue by JonathanetRaimond** [SocialGouv/carnet-de-bord#264]
- [x] Si on sélectionne d’autres aides que le RSA et qu’on enregistre, elles ne sont pas affichées. 
- [x] La date de naissance doit être modifiable

![4_Fiche_beneficiaire_1 2](https://user-images.githubusercontent.com/90344173/134594018-67497e45-9352-48b5-bd0c-a38b65ea7863.png)

**Comment by Augustin82** [comment]
Bug checkbox résolu dans 17c176cd10ec448676e3e401e93bf36c0f9571f2

**Comment by Augustin82** [comment]
@JonathanetRaimond il nous a semblé après test que la date de naissance est bien modifiable. Je te laisse nous dire si l'issue doit être rouverte.
