### ISSUE TITLE
Fiche bénéficiaire > Groupe de suivi > Inviter un accompagnateur > Ajouter un nouvel accompagnateur

### ISSUE THREAD

**Issue by JonathanetRaimond** [SocialGouv/carnet-de-bord#268]
- [x] Il manque le titre « Ajouter un nouvel accompagnateur » et la phrase « Recherchez un accompagnateur et envoyez une invitation à rejoindre le groupe de suivi de M. …… ».
- [x] Remplacer le texte du btn « Je valide mon inscription » par « Envoyer l’invitation ».

![4_Fiche_beneficiaire_3 2 3 4 1](https://user-images.githubusercontent.com/90344173/134593745-2e5d2c98-44fa-42d7-af00-34f848ec0d3b.png)

**Comment by lionelB** [comment]
creation dun compo ProNoteBookMemberForm 
modif du confirmText sur ProCreationForm
