### ISSUE TITLE
Fiche bénéficiaire > Axe de travail > Fiche contrat

### ISSUE THREAD

**Issue by JonathanetRaimond** [SocialGouv/carnet-de-bord#269]
- [x]  La date de signature doit être modifiable
- [x]  Lorsqu’un contrat est enregistré, on peut sélectionner un autre contrat (PPAE, CER,…) mais si on enregistre après avoir sélectionner « aucun contrat » on ne peut plus sélectionner un autre type de contrat car on ne pas sélectionner de date. 

![4_Fiche_beneficiaire_4 4](https://user-images.githubusercontent.com/90344173/134593664-3aa02aa3-930f-49cb-a079-b121261d9a06.png)

**Comment by lionelB** [comment]
ProNoteBookContract (mutation) supprimer la date obligatoire

**Comment by lionelB** [comment]
done in 352aa52a5f3244083850265840d6144adfcce3d9
