### ISSUE TITLE
Fiche bénéficiaire > Axe de travail > Fiche axe de travail

### ISSUE THREAD

**Issue by JonathanetRaimond** [SocialGouv/carnet-de-bord#270]
- [x] Lorsque l’axe de travail n’est pas lié à un contrat, remplacer le texte sous le titre « Aucun » par « Axe de travail non rattaché à un contrat »
- [x] Les intitulés de situation (Accès au droit, Pas d’avis d’impôt,…) doivent être à 16px.
- [ ]  Dans les objectifs le champ « Solliciter une structure » doit respecter le DSFR. Le btn doit être ferré à droite et les espaces entre les champs et le btn doivent être de 24px.
- [x]  Si il n’y a pas de structure sollicitée, le btn doit être désactivé et le texte « Voir toutes les structures (0) » remplacé par « Aucune structure sollicitées »

![4_Fiche_beneficiaire_4 3 3 2](https://user-images.githubusercontent.com/90344173/134593584-9cb2fe4f-9b2f-43ef-9183-b5fe1a230025.png)

**Comment by Augustin82** [comment]
J'archive. @JonathanetRaimond, ouvre une nouvelle issue si besoin.
