### ISSUE TITLE
admin - Permettre de renvoyer le lien de connexion 

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/carnet-de-bord#320]

**Comment by Augustin82** [comment]
@jonathanetraimond Je pense rajouter un bouton sous les infos Pro/Structure avec la date de dernier envoi du lien. Tu me dis si tu veux faire autrement.

**Comment by ronanjames** [comment]
Comment je peux documenter ? Je vous envoie les comptes déjà concernés ? 
Pour les MailinBlack, je pourrais leur demander d'aller faire une action sur leur ordi par ex ?

**Comment by lionelB** [comment]
on a deja fait une action pour mailinblack, les mail devraient arrivés.
si il y a d'autre problèmes il faudrait 
- voir avec la personne si c'est pas dans le spam
- si il y a un système de protection des mail type mailinblack
- nous prévenir pour qu'on analyse si c'est un pb de serveur de mail

**Comment by ronanjames** [comment]
Merci du retour, je vais leur renvoyer un lien et voir si les actions déjà faites règlent le pb, et leur rappeler d'aller vérifier leurs spams. 
Pour les bidouilles demandées par MailInBlack, on pourrait tenter ça jeudi si ça bloque encore par ex ? Si je peux le faire, n'hésitez pas à me dire (pour cliquer les boutons :))
