### ISSUE TITLE
[Refonte Interface] Création du concept de Territoire (Cohorte)

### ISSUE THREAD

**Issue by Augustin82** [SocialGouv/carnet-de-bord#342]
- création d'une table listant les Territoires d'expérimentation ;
- association du rôle d'admin actuel à un Territoire d'expérimentation (1 admin a 1 Territoire, 1 Territoire a N admin) ;
- création du rôle d'accountmanager (capable de créer des admins et des territoires et de les associer) ;
- rajout de la colonne accountmanager dans la table account ;
- modification des permissions sur la plupart des tables pour pré-filtrer par Territoire
- prévoir un script de migration pour la base de prod (création des Territoires existants, et des comptes admin attachés).

À discuter @lkouad @ronanjames @lionelB @renaudpons @jonathanetraimond.

**Comment by lionelB** [comment]
done in #361#370
