### ISSUE TITLE
 Implémenter l'import de bénéficiaires pour un pro (admin)

### ISSUE THREAD

**Issue by Augustin82** [SocialGouv/carnet-de-bord#378]
@jonathanetraimond @ronanjames pour cette feature, il faudrait qu'on creuse un peu (s'il y a peu de professionnels et beaucoup de bénéficiaires, on peut envisager de faire un upload par pro, par contre s'il y a beaucoup de pros, il faudrait proposer un import en batch, et donc trouver comment réaliser le lien entre pro et bénéficiaire au moment de l'upload.

**Comment by lionelB** [comment]
on peut fermer ?

**Comment by Augustin82** [comment]
Résolu par #404
