### ISSUE TITLE
Modifier le parser Marne pour intégrer les actions aux objectifs

### ISSUE THREAD

**Issue by Augustin82** [SocialGouv/carnet-de-bord#380]
Décider quoi faire pour le cas particulier de l'objectif sans nom qui a une ou plusieurs actions.

@ronanjames

A priori, aucune complexité technique pour une intégration simple de la liste d'actions.

**Comment by Augustin82** [comment]
Dans l'idéal, avancer là-dessus après une réunion avec Kevin.

**Comment by Augustin82** [comment]
Première réunion faite, on attend le retour.

**Comment by lionelB** [comment]
remplacé par #487
