### ISSUE TITLE
[Email] Changer l'adresse email de l'expéditeur des mails de l'appli CdB (.env)

### ISSUE THREAD

**Issue by Augustin82** [SocialGouv/carnet-de-bord#425]

**Comment by lionelB** [comment]
Je me demande si les demandes de validation ne devrait être envoyées aux personnes idéntifiées qui gèrent les structures
C'est un rôle qu'on a pas mais qu'on pourrait créer

**Comment by lionelB** [comment]
cf ce thread https://mattermost.incubateur.net/betagouv/pl/86aoagefciny9qgw8bqe8do4je

**Comment by lionelB** [comment]
oui pour le changement d'adresse vers `support`
