### ISSUE TITLE
Modification en base des données de parcours pour l'import des nvx Carnets 93

### ISSUE THREAD

**Issue by ronanjames** [SocialGouv/carnet-de-bord#431]
L'import des données d'identification est effectif 
l'import actuel ne permet pas d'importer les données de suivi et de rattacher des nouveaux pro à des carnets existants 
L'import des informations sur les carnets transmis par le 93 entre septembre et octobre, il faut mettre à jour ses informations en base. 
L'objectif est bien de solder une situation provenant de la phase d'expé, pas d'avoir ce type de process pour les futurs nouveaux carnets. 
Ronan envoie aux devs les champs à MAJ par Carnets

**Comment by Augustin82** [comment]
@ronanjames suite au retour de mes mises à jour, tu nous diras si tu veux qu'on fasse d'autres actions.

**Comment by Augustin82** [comment]
J'archive. @ronanjames, tu peux ouvrir une nouvelle issue si tu as besoin.
