### ISSUE TITLE
UI > reprendre les page existantes en suivant les maquettes + DSFR

### ISSUE THREAD

**Issue by tglatt** [SocialGouv/carnet-de-bord#46]
Les maquettes respectent le design system de l'état: 

https://gouvfr.atlassian.net/wiki/spaces/DB/pages/193003540/COMMENT%2BUTILISER%2BLE%2BDSFR

reprendre les pages existantes pour qu'elle respecte les maquettes:
- `/auth/login`
- `/pro/welcome`
- `/pro/annuaire`
- `/pro/beneficiaire/{uuid}`

Il faut commencer à créer des composant de bases respectant le DSFR. On pourrait les mettre dans `src/lib/ui/base`. On pourra s'inspirer de : https://github.com/dataesr/react-dsfr

Pour le moment, on utilise tailwindcss. Pas sur qu'on en est encore besoin avec l'intégration de DSFR. 

[WIREFRAME_CDB_CONNEXION_30-07-2021.pdf](https://github.com/SocialGouv/carnet-de-bord/files/6905629/WIREFRAME_CDB_CONNEXION_30-07-2021.pdf)
[WIREFRAME_CDB_GENERAL_30-07-2021.pdf](https://github.com/SocialGouv/carnet-de-bord/files/6905630/WIREFRAME_CDB_GENERAL_30-07-2021.pdf)

**Comment by Augustin82** [comment]
Pour info : à mon sens, tout est bon niveau visuel, sauf la page bénéficiaire.

L'ajout de bénéficiaire n'est pas implémenté, et le filtre (le dropdown avec la période, pas la recherche textuelle) non plus.

**Comment by tglatt** [comment]
#121
