### ISSUE TITLE
Quand j’ai oublié mon identifiant je dois saisir mon adresse email pour recevoir mon identifiant et un lien magique

### ISSUE THREAD

**Issue by tglatt** [SocialGouv/carnet-de-bord#48]
A partir de la page de login, je peux cliquer sur:
- j'ai oublié mon identifiant
- je peux renseigner mon email
- je reçois un email avec mon nom d'utilisateur et un lien magique pour accéder à mon espace

Voir les maquettes

**Comment by Augustin82** [comment]
Résolu par https://github.com/SocialGouv/carnet-de-bord/commit/225629c44aa6a21c08a2b25ec03f00c82aad0bfd
