### ISSUE TITLE
Permettre la mise à jour à partir des imports CSV

### ISSUE THREAD

**Issue by ronanjames** [SocialGouv/carnet-de-bord#489]
**Problème**

L’import par CSV permet d’initialiser les Carnets mais pas de les mettre à jour par import

**Pistes évoquées** 

“Pour de la mise a jour, il faut qu'on mettent en place un système pour gérer les conflits et concernant le groupe de travail, ca se fera via un autre fichier car en l'etat on ne pourra pas appliquer les modifs sans ecraser ce qui a été modifié par un accompagnateur” @lionelB

**Comment by lkouad** [comment]
Concernant les modifs fait par un autre accompagnateur tu parles de quoi? @ronanjames 
Si j'ai bien compris l'import accompagnateur n'est pas liée à axe de travail? @lionelB

**Comment by ronanjames** [comment]
J'ai indiqué la situation actuelle et repris la piste évoquée par Lionel. 
De ce que je comprends, il faudrait s'assurer qu'on peut mettre à jour par imports csv : 
- les champs du CSV nvx 1 
- la liste des accompagnateurs du groupe de travail 
- les axes de travail (pas encore de CSV d'import à ce stade)

**Comment by lkouad** [comment]
Donc du coup je ne comprend pas pourquoi ça écrase les données 
Ne pourrions nous pas ajouter une date de debut et une date de fin à un accompagnateur dans un groupe de suivi @lionelB 
Ce qui nous permet de garder l'accompagnateur dans le groupe de suivi l'objectif étant pour le nouvelle accompagnateur de se coordonner avec l'ancien

**Comment by lionelB** [comment]
Un exemple : 
> groupe de suivi initial: Jean michel
> jean michel invite jean louis
> puis le lendemain, on lance la mise a jour qui nous dit c'est JeanMichel 

les questions à trancher quand on veut mettre à jour depuis un CSV 

Est ce que les mise à jour ne contiennent que des données qui ont changées  vs on lance la récupération de manière automatique;
Est ce qu'on suppose que la mise a jour a toujours raison (auquel cas on perd l'info que Jean louis a été invité)
Est ce que l'on applique un modification seulement si l'info a changé depuis la dernière fois 
Est ce qu'on bloque la mise à jour si l'info carnet de bord est plus récente (dans le cas ou on aurait des dates de mise a jour cote csv)
Est ce qu'on ne fait qu'ajouter dans le groupe de suivi ?

on peut rajouter des dates mais je ne pense pas que ça réponde au besoin de savoir qui a raison ou pas lors d'une mise a jour.
