### ISSUE TITLE
Ajouter un statut/historique à la relation notebook_member

### ISSUE THREAD

**Issue by Augustin82** [SocialGouv/carnet-de-bord#502]

**Comment by Augustin82** [comment]
Ça permet de savoir qui a suivi une personne, ça permet au gestionnaire de structure de connaître les dossiers suivis ou qui ont été suivis par sa structure.

**Comment by lionelB** [comment]
solution retenue pour l'instant: utilisation d'un flag "active" qui permet de voir qui fait partie / a fait partie du groupe de suivi (pas d'info sur les périodes) #643
