### ISSUE TITLE
[Admin PDI] Recevoir un mail quand l'Admin CdB crée un nouveau déploiement

### ISSUE THREAD

**Issue by Augustin82** [SocialGouv/carnet-de-bord#507]

**Comment by Augustin82** [comment]
Je viens de tester sur https://carnet-de-bord-epic-admin-542e8h.dev.fabrique.social.gouv.fr/admin et ça marche. @lkouad quel problème as-tu rencontré ?

**Comment by lkouad** [comment]
Top test ok
