### ISSUE TITLE
Créer un compte et lancer l'onboarding pour le Gestionnaire de structure, si nécessaire

### ISSUE THREAD

**Issue by Augustin82** [SocialGouv/carnet-de-bord#508]

**Comment by lkouad** [comment]
Test KO https://github.com/SocialGouv/carnet-de-bord/pull/538#issuecomment-1024399070

**Comment by lkouad** [comment]
https://github.com/SocialGouv/carnet-de-bord/projects/4#card-76466958

**Comment by Augustin82** [comment]
Il y avait un problème de migration pas passée sur le déploiement, normalement maintenant c'est possible de créer un gestionnaire de structure (cf. https://github.com/SocialGouv/carnet-de-bord/pull/584#issuecomment-1031916370)

**Comment by lkouad** [comment]
Yep testé ok

**Comment by lionelB** [comment]
done in #538
