### ISSUE TITLE
Importer les structures d’accompagnement de mon territoire 

### ISSUE THREAD

**Issue by lkouad** [SocialGouv/carnet-de-bord#521]
ETQ Admin PDI je peux importer les structures d’accompagnement de mon territoire afin de les référencer et de leur permettre un accès à CDB

# Présentation
https://instinctive-tarragon-76f.notion.site/V1-Import-Donn-e-parcours-BRSA-f5fb585ecee0486bad5be1eab2ff59f2

## Proposition de travail
Nom structure*Ville*Adresse, Adresse (complement) Téléphone, Courriel, site web SIRET Description, nom du gestionnaire de la structure*, prénom du gestionnaire de la structure*, fonction du gestionnaire de la structure*, adresse mail du gestionnaire de la structure*, téléphone du gestionnaire de la structure
## Designs

[Maquette Admin Cohorte PDI](https://www.figma.com/file/YsikssTwIOl9OaSZMaeybe/MAQ-ADMIN-PDI-V2?node-id=0%3A1)

## Evolution à prévoir
Je peux supprimer une structure (généralement pour le département 1 fois par an)

**Comment by lionelB** [comment]
# Import de structure

## Modèle 
[import-structure.csv](https://github.com/SocialGouv/carnet-de-bord/files/7933631/import-structure.csv)
| nom | description | téléphones | adresses 1 | addresse 2 | code postal | ville | site web | siret | email responsable | prenom responsable | nom responsable | téléphones responsable | fonction responable |
|--|--|--|--|--|--|--|--|--|--| -- | -- |--| -- |
|CD 26| Conseil departemental de la Drôme (26) | 0601234567; 071234567 |14 chemin de la liberté | 2ieme étage | 26270|Loriol sur Drôme |https://carnet-de-bord.fabrique.gouv.fr|12000015300011 | jean.paul@marne.fr | jean | paul | responsable | 061234567; 091234567 | 

        
### nom (unique)
Nom de la structure
type: texte
ex: Conseil departemental de la Drôme (26)

### description (champ facultatif)
Description courte de la structure
type: texte
ex: Département de la drôme

### téléphones (champ facultatif)
Liste de numéro de téléphone, séparée par un point virgule
type: texte
ex: 0601234567; 071234567

### adresse 1 (champ facultatif)
type: texte
ex: 14 chemin de la liberté

### adresse 2 (champ facultatif)
type: texte
ex: 2ieme étage

### code postal
type: nombre
format: 5 chiffres
ex: 26270


### ville 
type: texte
ex: Loriol sur Drôme

### site web (champ facultatif)
type: texte
format: doit commencer par http:// ou https://
ex: https://carnet-de-bord.fabrique.gouv.fr

### siret (champ facultatif)
type: nombre
format: 14 chiffres
ex: 12000015300011


### email responsable
Email de la personne qui sera le gestionnaire de cette structure dans Carnet de Bord. 
type: texte
ex: jean.paul@marne.fr

### prénom responsable
type: texte
ex: Jean

### nom responsable
type: texte
ex: Truc
### téléphones responsable
Liste de numéro de téléphone, séparée par un point virgule
type: texte
ex: 061234567; 091234567

### fonction responsable
type: texte
ex: Directeur d'agence

**Comment by lionelB** [comment]
todo: 

- [ ] - creation des tables gestionnaire structure, beneficiaire_structure
- [ ] - migration de la base prod
- [ ] - ajout de la page d'accueil / bouton d'import
- [ ] - test e2e

**Comment by lkouad** [comment]
https://github.com/SocialGouv/carnet-de-bord/pull/538#issuecomment-1024257994

**Comment by lionelB** [comment]
done in #538
