### ISSUE TITLE
Importer les données des bénéficiaires afin de creer les carnets de bord.

### ISSUE THREAD

**Issue by lkouad** [SocialGouv/carnet-de-bord#523]
Importer les données des bénéficiaires afin de creer les carnets de bord.
# Présentation

## Proposition de travail
Depuis son compte il peut, créer, mettre à jour à Bénéficiaires > Identifiant dans le SI* Prenom* Nom* Date de naissance* Tel Email Adresse Adresse (complément) Zip Ville Situation Numero allocaire Caf Identifiant Pole emploi Droits RSA Droits ARE Droits ASS Prime d'activité AAH Zone de mobilité Emploi recherché (code ROME) Niveau de formation Date de signature du CER Nom structure*Ville de la structure*Adresse de la structure, Adresse (complement) de la structure

Attention cas particulier des Ardenne X structures pour 1 BRSA
Attention Cas particulier accompagnement global 2 structures pour BRSA

**Comment by Granedal** [comment]
a

**Comment by lkouad** [comment]
KO sur cet import: 
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/kouadria/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/kouadria/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Identifiant dans le   SI* | PrÃ©nom* | Nom* | Date de naissance* | TÃ©lÃ©phone | Email | Adresse | Adresse (complÃ©ment) | Code postal | Ville | Situation | NumÃ©ro allocaire CAF/MSA | Identifiant PÃ´le emploi | Droits RSA | Droits ARE | Droits ASS | Prime d'activitÃ© | AAH | Zone de mobilitÃ© | Emploi recherchÃ© (code ROME) | Niveau de formation | Structure | Accompagnateurs
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1234 | Charlotte | Fondue | 25/05/1998 | 0601234567, 071234567 | charlotte@laposte.fr | 11 rue du Fromage | Lieu-dit "Le sandwich" | 61120 | Camembert |   | 2055990 | 300000L | rsa_droit_ouvert_et_suspendu | Oui | Non |   | between_20_30 | Pontier Ã©lingueur / PontiÃ¨re Ã©lingueuse (N1104) | level_6 | PÃ´le emploi de Normandie
1236 | Charlot | Tordue | 25/05/1978 | 0601234568, 071234562 | charlot@laposte.fr | 12 rue du L'equere | Lieu-dit "L'angle droit" | 61120 | Camembert |   | 2055992 | 300000X | rsa_droit_ouvert_et_suspendu | OUI | OUI |   |   | level_6 |   | cathy@lyon.fr,diane-lyon1@emmaus.fr



</body>

</html>

![image](https://user-images.githubusercontent.com/83343517/152861449-72c9a87c-5a5b-4507-a8f6-115aa4d6daab.png)
Identifiant dans le SI*	PrÃ©nom*	Nom*	Date de naissance*	TÃ©lÃ©phone	Email	Adresse	Adresse (complÃ©ment)	Code postal	Ville	Situation	NumÃ©ro allocaire CAF/MSA	Identifiant PÃ´le emploi	Droits RSA	Droits ARE	Droits ASS	Prime d'activitÃ©	AAH	Zone de mobilitÃ©	Emploi recherchÃ© (code ROME)	Niveau de formation	Structure	Accompagnateurs
1234	Charlotte	Fondue	25/05/1998	0601234567, 071234567	charlotte@laposte.fr	11 rue du Fromage	Lieu-dit "Le sandwich"	61120	Camembert		2055990	300000L	rsa_droit_ouvert_et_suspendu		Oui	Non		between_20_30	Pontier Ã©lingueur / PontiÃ¨re Ã©lingueuse (N1104)	level_6	PÃ´le emploi de Normandie	
1236	Charlot	Tordue	25/05/1978	0601234568, 071234562	[charlot@laposte.fr](mailto:charlot@laposte.fr)	12 rue du L'equere	Lieu-dit "L'angle droit"	61120	Camembert		2055992	300000X	rsa_droit_ouvert_et_suspendu			OUI	OUI			level_6		cathy@lyon.fr,diane-lyon1@emmaus.fr

**Comment by Augustin82** [comment]
> KO sur cet import: ![image](https://user-images.githubusercontent.com/83343517/152861879-e888515c-d771-4bd8-af34-9ba77c105f11.png)

Tu as testé sur quel environnement (quelle URL) s'il te plaît ?

**Comment by lkouad** [comment]
J'ai testé sur https://carnet-de-bord-epic-admin-542e8h.dev.fabrique.social.gouv.fr/ avec le compte manager.cd51 
Je viens de refaire la test, j'utilise le modèle modifie la 2 éme ligne comme ci dessus et ko, J'ai loupé un truc?
![image](https://user-images.githubusercontent.com/83343517/152875573-849192e0-775a-4a9d-96cf-bd46b4dc47b5.png)

**Comment by Augustin82** [comment]
OK, je pense savoir pourquoi : tu ouvres le modèle dans Excel, il te l'interprète, utilise un autre encodage au passage (d'où les caractères cabalistiques), transforme le format de date en un truc qu'on ne sait pas parser, change peut-être d'autres choses, et du coup ça ne marche plus.
Dans ton fichier, la date est JJ/MM/AAAA alors que la notice de remplissage précise que c'est AAAA-MM-JJ. Essaye de faire tes modifications en ouvrant le fichier .csv de modèle comme du texte (dans Notepad par exemple), pour voir ?
Et, évidemment, la question du support élargi des fichiers d'import est légitime, hein (c'est juste que c'est un peu l'enfer, vu le format xlsx).

**Comment by lkouad** [comment]
Ha lol bon je m'en doutais mais bêtement j'ai juste regardé que le format était bien "type csv" sur ordi j'avais pas pensé qu'il transformerait sorry :)

**Comment by lkouad** [comment]
Du coup top :) test ok

**Comment by Augustin82** [comment]
> Ha lol bon je m'en doutais mais bêtement j'ai juste regardé que le format était bien "type csv" sur ordi j'avais pas pensé qu'il transformerait sorry :)

C'est pas du tout ta faute, et clairement ça va poser problème à terme =/

**Comment by lionelB** [comment]
done in #584
