### ISSUE TITLE
Voir dans la liste des  BRSA qui sont confiés à ma structure s’ils ont bien reçu un accompagnateur

### ISSUE THREAD

**Issue by JonathanRaimond** [SocialGouv/carnet-de-bord#526]
## Problématique
le gestionnaire de structure encadre l'équipe référent de sa structure doit pouvoir organiser, coordonner et superviser les activités de son équipe.
Il est régulièrement amené à régler les difficultés entre le bénéficiaire et le référent et peu régulièrement prendre le relais sur des dossier pour débloquer des situations  
##### Son rôle: 
Rattache des accompagnateurs à des bénéficiaires
S’assure que l’accompagnateur rencontre le bénéficiaire
Régler les litiges
Réoriente le cas échéant (out scope v0)
##### Besoins
S’assurer de la prise en charge du bénéficiaire par l’accompagnateur
Suivre la signature du CER PPAE....
Accéder aux carnets
Faire des changements de référent en interne (turnover, absence, changement....)
Faire les demandes de réorientation(out scope V0)

## Proposition de travail
Depuis son interface lui permettre d'avoir une liste de bénéficiaire afin d'identifier visuellement ceux qui n'ont pas de référent, les non prise en charge d'accompagnement et gérer les changements (v0)
#### Donnée visible :
- Nom Prenom du bénéficiaire
- Nom Prenom Accompagnateur de la structure (ne pas afficher les accompagnateurs des autres structures"
1 Si pas d'accompagnateur afficher "non rattaché"
1.A Si clique sur "non rattaché" ouvrir "rattacher un accompagnateur"
https://github.com/SocialGouv/carnet-de-bord/issues/532
2. Si accompagnateur dans ma structure alors affiche nom prénom de l'accompagnateur
2.A Si clique sur le nom prenom de l'accompagnateur alors ouvrir " modifier le référent"
https://github.com/SocialGouv/carnet-de-bord/issues/525
- Depuis le : Date d'ajout de l'accompagnateur au groupe de suivi
- Voir le carnet https://github.com/SocialGouv/carnet-de-bord/issues/530
#### Recherche rapide V0
- Nom Bénéficiaire
- Numéro Caf
- Nom accompagnateur
#### Filtre de la liste V0
- Non rattaché

# Designs
@JonathanRaimond  re faire la maquette comme dans l'image

https://www.figma.com/file/BzTnRSf5KczPTuQeFEgQft/MAQ-GEST-STRUCTURE-V2?node-id=0%3A1

![Bénéficiaires-liste](https://user-images.githubusercontent.com/85908681/157644384-cd11e2ba-5c2e-433b-81b2-c42e00b14328.png)

![Bénéficiaires-Filtres](https://user-images.githubusercontent.com/85908681/157643414-05e3ae24-2b90-4889-908c-23700aeb74aa.png)

![Bénéficiaires-Rattachement-1](https://user-images.githubusercontent.com/85908681/157643435-f01d3ac0-93e8-4515-95ab-6a04b4fb0118.png)

![Bénéficiaires-Rattachement-2 1](https://user-images.githubusercontent.com/85908681/157643453-5d695f72-b023-4720-826b-cf172a94a6f8.png)

![Bénéficiaires-Rattachement-2 2](https://user-images.githubusercontent.com/85908681/157643466-75dcab5a-2257-495b-935b-1e9409e138b5.png)

**Comment by lkouad** [comment]
@JonathanRaimond  faut refaire un zoning V0 à discuter Mardi
