### ISSUE TITLE
Importer des listes des accompagnateurs

### ISSUE THREAD

**Issue by JonathanRaimond** [SocialGouv/carnet-de-bord#527]
### Présentation
ETQ gestionnaire de structure je souhaite Importer la liste des accompagnateurs de ma structure afin de ne pas saisir manuellement et individuellement les informations
## Problématique
Les gestionnaires de structure ne sont pas forcement tous habitués à importer des fichiers, il faut donc mettre en place un système simple d'import et bien "tutorer" les étapes.
## Proposition de travail
Depuis son espace gestionnaire de structure l'utilisateur doit identifier rapidement la possibilité d'importer ses accompagnateurs et gérer l'import.
nom accompagnateur de la structure*, prénom accompagnateur de la structure*, fonction accompagnateur de la structure*, adresse mail accompagnateur de la structure*, téléphone du accompagnateur de la structure
# Critères de réussite
1. L'utilisateur crée le fichier  depuis un model téléchargeable dans son espace import accompagnateur
2. Il peux prévisualise le résultat de l'import
3. Résultat de l'importation est  montré via la liste des accompagnateurs

# Exigences
1. Le système vérifie l'intégrité des champs et vérifie les doublons
2. . L'utilisateur doit avoir accès aux exceptions ignorées (erreurs, doublons) et le nombre d'accompagnateur créés

# Designs
[Maquette Gestionnaire de structure](https://www.figma.com/file/BzTnRSf5KczPTuQeFEgQft/MAQ-GEST-STRUCTURE-V2?node-id=0%3A1)

# Alternatives envisagées
Saisie manuel via formulaire: impossible certaines structures on plus de 1000 CIP....

# Evolution à challenger
L'utilisateur valide l'import, le système lui indique d'un email de confirmation d'import lui sera envoyé
Compter le nombre d'import interrompu

**Comment by lionelB** [comment]
done in #606
