### ISSUE TITLE
Gérer les comptes de collaborateurs

### ISSUE THREAD

**Issue by JonathanRaimond** [SocialGouv/carnet-de-bord#528]
ETQ gestionnaire de structure  Je dois gérer les comptes de collaborateurs
# Présentation
ETQ gestionnaire de structure  Je dois gérer les comptes de collaborateurs afin de faire des mises à jour
## Problématique
Il est impossible ^pour un gestionnaire de supprimer le compte d'un accompagnateur. 

## Proposition de travail
Le turn over étant important il doit pouvoir fermer l'accès à un accompagnateur
Les données d'accompagnement ne doivent pas disparaitre.
Le nom de l'accompagnateur doit rester lisible après retrait des droits
L'accompagnateur doit être retiré du groupe de suivi 
Son accompagnement doit être archivé
liste des pro

# Designs

[Maquette Gestionnaire de structure](https://www.figma.com/file/BzTnRSf5KczPTuQeFEgQft/MAQ-GEST-STRUCTURE-V2?node-id=0%3A1)

**Comment by lkouad** [comment]
@JonathanRaimond revoir la maquette
