### ISSUE TITLE
Ajouter un accompagnateur 

### ISSUE THREAD

**Issue by JonathanRaimond** [SocialGouv/carnet-de-bord#532]
### Présentation
ETQ gestionnaire de structure: Je peux ajouter un accompagnateur de ma structure au groupe de suivi du carnet de bord d'un bénéficiaire afin de notifier la prise en charge par l’accompagnateur
## Problématique
Le gestionnaire de structure doit pouvoir rattacher les bénéficiaires à X accompagnateurs de sa structure mais le choix du rattachement peut être fait selon certain critères
## Proposition de travail
Depuis son espace gestionnaire de structure l'utilisateur doit pouvoir accéder à la liste de des bénéficiaires de sa structure et identifier rapidement ceux qui ne sont pas pris en charge afin de leur rattacher un accompagnateur ex: dans la marne par attribution selon les lettres de l’alphabet, dans d’autre structure attribution selon la localisation, selon l’âge, le type d’accompagnement, le type de frein… Le gestionnaire de structure doit pouvoir s’assurer que la prise en charge du bénéficiaire est bien effective
# Critères de réussite
1.	Pouvoir filtrer la liste des bénéficiaires sans accompagnateurs
2.	Pouvoir filtrer cette liste par critère 
3.	Pouvoir réattribuer les bénéficiaires de l’accompagnateur X à l’accompagnateur Y rapidement
4.	Pouvoir identifier que l’accompagnateur a pris connaissance du carnet
# Exigences
1.	Le système permet de filtrer et propose le choix des données le plus large possible
2.	Le système permet de réattribuer en masse les bénéficiaires à un autre accompagnateurs
3.	Le système permet de s’assurer que l’accompagnateur a ouvert le carnet

# Designs
[Maquette Gestionnaire de structure](https://www.figma.com/file/BzTnRSf5KczPTuQeFEgQft/MAQ-GEST-STRUCTURE-V2?node-id=0%3A1)

# Alternatives envisagées
L’accompagnateur peux aussi se rattacher à un bénéficiaire de sa structure

**Comment by lkouad** [comment]
Ajouter un bouton dans la liste des actions (maquette KO @JonathanRaimond )
