### ISSUE TITLE
Gerer le statut d'une action

### ISSUE THREAD

**Issue by JonathanRaimond** [SocialGouv/carnet-de-bord#560]
### **Problématique**
Le professionnel est garant du suivi de parcours des bénéficiaire, il ne peux pas mettre à jour l'état d'avancement des démarches

### **Proposition de travail**
Lui permettre de mettre à jour le statut d'une action dans l'objectif d'un axe de travail
Commencer par tester avec les statuts en menu déroulant  En cours/ Réalisée /Abandonnée
### Out Scope
Nous sommes sur une saisie Manuelle nous investiguerons plus tard comment mettre à jour cette donnée hors saisie manuelle
### Dépendance:
https://github.com/SocialGouv/carnet-de-bord/issues/561

### **Designs**
![image](https://user-images.githubusercontent.com/83343517/152434449-5fad97c8-2e70-4ee5-892e-f1acc55dfe82.png)

### **Origine**
Atelier Utilisateur
Retour Utilisateur

### **Business Value**
Améliore le travail des utilisateurs, 
Garantie une meilleure stabilité du produit
Indispensable pour d’autres epics

**Comment by lionelB** [comment]
Modifier la table action pour rajouter un champs status (pending / done / aborted, abandonned, forsaken) et probablement un champ jsonb dans lequel on pourrait stocké le `professionnalId`
est ce qu'on veut pouvoir tracké l'ensemble des changements opérés ou seulement le dernier ?
