### ISSUE TITLE
Historiser les actions

### ISSUE THREAD

**Issue by JonathanRaimond** [SocialGouv/carnet-de-bord#561]
### **Problématique**
Le professionnel a besoin d'identifier les démarches réalisées lors du parcours du bénéficiaire, il ne peux pas consulter les actions réalisées ou abandonnées dans l'historique de parcours.

### **Proposition de travail**
Historiser les actions réalisées ou abandonnées dans l'historique de parcours en v0

### **Design**
![Capture d’écran 2022-03-22 à 19 00 10](https://user-images.githubusercontent.com/85908681/159546001-220e5933-a0c6-44cc-87e1-35e9729bb618.png)

### **Origine**
Atelier Utilisateur

### **Business Value**
Améliore le travail des utilisateurs, 
Garantie une meilleure stabilité du produit
Indispensable pour d’autres epics

**Comment by lionelB** [comment]
https://github.com/SocialGouv/carnet-de-bord/issues/563#issuecomment-1060387164

**Comment by vjousse** [comment]
En cours avec #563 sur #736
