### ISSUE TITLE
Gerer le statut d'un objectif

### ISSUE THREAD

**Issue by JonathanRaimond** [SocialGouv/carnet-de-bord#562]
### **Problématique**
Le professionnel est garant du suivi de parcours des bénéficiaire, il ne peux pas mettre à jour l'état d'avancement des démarches

### **Proposition de travail**
Lui permettre de mettre à jour le statut d'un objectif dans un axe de travail
Commencer par le statut En cours/ réalisée/Abandonnée
### Out scope
Nous sommes sur une saisie Manuelle nous investiguerons plus tard comment mettre à jour cette donnée hors saisie manuelle
### Dépendance:
https://github.com/SocialGouv/carnet-de-bord/projects/4#card-76929726

### **Designs**
Wireframe à terminer

### **Origine**
Atelier utilisateur

### **Business Value**
Améliore le travail des utilisateurs, 
Garantie une meilleure stabilité du produit
Indispensable pour d’autres epics

**Comment by lionelB** [comment]
Modifier la table Object pour rajouter un champ  `status` (pending / done / aborted, abandonned, forsaken) et probablement un champ jsonb dans lequel on pourrait stocké le professionnalId de la personne qui fait la modif
est ce qu'on veut pouvoir tracké l'ensemble des changements opérés ou seulement le dernier ?

le fait de modifier le status de objectif (done / aborted)  ne modifie pas les statut des actions lié à l'objectif.

Un objectif avec un status autre que pending devra pouvoir remonté dans l'historique de parcours
