### ISSUE TITLE
Historiser les objectifs

### ISSUE THREAD

**Issue by JonathanRaimond** [SocialGouv/carnet-de-bord#563]
### **Problématique**
Le professionnel a besoin d'identifier les démarches réalisées lors du parcours du bénéficiaire, il ne peux pas consulter les objectifs réalisés ou ne pouvant être réalisés dans l'historique de parcours.

### **Proposition de travail**
Historiser les objectifs réalisés ou ne pouvant pas être réalisés dans l'historique de parcours

### **Design**
![Capture d’écran 2022-03-22 à 19 00 10](https://user-images.githubusercontent.com/85908681/159545908-74ffa043-42bd-4f0a-8992-04990af75b41.png)

### **Origine**
Atelier utilisateur

### **Business Value**
Améliore le travail des utilisateurs

**Comment by lionelB** [comment]
Dans le dernier item de l'accordéon du carnet bénéficiaire (Historique de parcours); 
Les infos proviennent d'une table notebook_event (cense etre alimenter par des sourcs externes) et qui n'est pour l'instant pas utilisé. 
Dans cette PR; il faudrait faire remonter les objectifs / actions dont le statut n'est pas "pending". 
On verra dans le futur comment on pourra afficher à la fois des évenement exterieurs et des objects / actions passés

**Comment by vjousse** [comment]
En cours sur #736
