### ISSUE TITLE
Ajouter une date de fin prévisionnelle à un type de contrat 

### ISSUE THREAD

**Issue by JonathanRaimond** [SocialGouv/carnet-de-bord#575]
Problème
Actuellement nous enregistrons uniquement la date de signature d'un contrat ce qui ne permet pas de suivre la réalisation de celui ci
Solution:
Ajouter une date de début une date de fin prévisionnelle:
- la date de début
- Durée de contrat
- date de signature
- la date de fin prévisionnelle

Scenario#1 : L'utilisateur ajoute une date de fin prévisionnelle

Les critères d'acceptation

Étant donné que j'ai ajouté un type de contrat et que j'ajoute une date début
1/ Lorsque je rentre une date de fin prévisionnelle postérieur à la date de début et que la durée se calcul automatiquement
Alors je peux consulter sur l'écran d'accueil du bénéficiaire la date de début, la date de fin et la durée du contrat " Du xx/xx/xxxx au xx/xx/xxxx ( x mois)

2/Lorsque je rentre une date de fin prévisionnelle antérieur à la date de début
Alors le systeme affiche un message "Veuillez sélectionner une date de fin valide"

3/ Lorsque je rentre une date de fin prévisionnelle postérieur à la date de début et que souhaite changer la durée de la situation
Alors le systéme affiche un message d'erreur "Veuillez modifier ou supprimer la date de fin prévisionnelle"

Scenario#2 : L'utilisateur ajoute une durée

Les critères d'acceptation

Étant donné que j'ai ajouté un type de contrat et que j'ajoute une date début

1/ Lorsque je rentre une durée en mois
Alors je peux consulter la date de fin prévisionnelle qui se calcul automatiquement

2/Lorsque je rentre une durée et que je veux modifier la date de fin prévisionnelle
Alors le systeme affiche un message "Veuillez modifier ou supprimer la durée"

Scenario#3 : L'utilisateur ajoute une date de début 

Les critères d'acceptation

Étant donné que j'ai ajouté un type de contrat  et que j'ajoute une date début
1/ Lorsque je n'ajoute pas de durée ou de fin et que je valide
Alors systéme affiche "depuis le" sur l'écran d'accueil

Scenario#4 : L'utilisateur ajoute une date de signature

Les critères d'acceptation

Étant donné que j'ai ajouté un type de contrat  et que j'ajoute une date début
1/ Lorsque j'ajoute une date de signature
Alors systéme affiche "signé" sur l'écran d'accueil

Besoins futures.

Cette information pourrait apparaitre dans l'historique en V1

**Comment by lkouad** [comment]
@Lotphy 
1/ Il manque l'affichage sur le devant
Étant donné que j'ai ajouté un type de contrat et que j'ajoute une date début
1/ Lorsque je rentre une date de fin prévisionnelle postérieur à la date de début et que la durée se calcul automatiquement
Alors je peux consulter sur l'écran d'accueil du bénéficiaire la date de début, la date de fin et la durée du contrat " Du xx/xx/xxxx au xx/xx/xxxx ( x mois)

**Comment by lkouad** [comment]
@Lotphy le calcul de la date de fin se fait à partir de la date de debut qui est différente et indépendante de la date de signature

Scenario#3 : L'utilisateur ajoute une date de début

Les critères d'acceptation

Étant donné que j'ai ajouté un type de contrat et que j'ajoute une date début
1/ Lorsque je n'ajoute pas de durée ou de fin et que je valide
Alors systéme affiche "depuis le" sur l'écran d'accueil

**Comment by lkouad** [comment]
@Lotphy Il doit y avoir la date de debut, la date de fin prévisionnelle et la date de signature
La date de signature
Scenario#4 : L'utilisateur ajoute une date de signature
Les critères d'acceptation
Étant donné que j'ai ajouté un type de contrat et que j'ajoute une date début
1/ Lorsque j'ajoute une date de signature
Alors systéme affiche "signé" sur l'écran d'accueil

**Comment by lionelB** [comment]
done in https://github.com/SocialGouv/carnet-de-bord/pull/840
