### ISSUE TITLE
[barre de recherche] annuaire ou groupe de suivi

### ISSUE THREAD

**Issue by lkouad** [SocialGouv/carnet-de-bord#592]
La prise en compte des accents est trop bloquante 
Retour terrain: recherche Valérie écrit Val(e)rie pas de suggestion
Origine:
Retour Utilisateur
Business Value:

**Comment by vjousse** [comment]
Au cas où ça serait intéressant à l'avenir, je consigne cela ici.

Premier essai infructeux en essayant d'utiliser les `tsquery`. On veut pouvoir matcher que des parties du nom et les `tsquery` ne permettent pas cela pour l'instant. On peut matcher des prefixes avec des query du style 'sophi:*' mais on ne peut pas matcher _au milieu_.

```SQL
SELECT *
FROM (SELECT beneficiary.id,
             beneficiary.email,
             to_tsvector('simple', unaccent(beneficiary.lastname)) ||
             to_tsvector('simple', unaccent(beneficiary.firstname)) ||
             to_tsvector('simple', beneficiary.pe_number) ||
             to_tsvector('simple', beneficiary.caf_number) ||
             to_tsvector('simple', beneficiary.mobile_number)
      as document
      FROM beneficiary) p_search
WHERE p_search.document @@ to_tsquery('simple', unaccent('ophie'));
```

**Comment by vjousse** [comment]
En revanche, la combinaison de `pg_trm` et de `unaccent` nous permet de matcher des noms mal orthopgraphiés et mal accentués.

```SQL
SELECT *
FROM beneficiary
WHERE
  (unaccent('tifôr') <% lastname OR '300000L' <% pe_number OR '205590' <% caf_number OR '060606060' <% mobile_number)
  ```
Cette requête va par exemple nous retourner Sophie Tifour même si son nom est écrit `tifôr`, qu'il manque un numéro dans son numéro Pôle Emploi et un numéro dans son numéro de téléphone. Je pense que nous devrions choisir cette voie en réglant la sensibilité avec `pg_trgm.strict_word_similarity_threshold` si besoin.
