### ISSUE TITLE
Intégration référentiel axe de travail

### ISSUE THREAD

**Issue by lkouad** [SocialGouv/carnet-de-bord#593]
Probléme:
Le référentiel qui à été intégré est trop Marnais et ne correspond pas aux autre départements du coup les utilisateurs ne peuvent pas pleinement Axe de travail
ex:
![image](https://user-images.githubusercontent.com/83343517/152302580-7ca5fedc-51e5-4ce4-bb9e-06414c8991d7.png)
Solution:
Intégrer un référentiel plus commun

**Comment by lionelB** [comment]
Impact 
- Modification du mapping avec les actions de la marne

Réflechir si le stockage du référentiel en BDD reste pertinent

**Comment by lkouad** [comment]
@lionelB voici le mapping avec les actions de la marne @ronanjames à fait le point avec 3 cd + CAF et c'est ok https://docs.google.com/spreadsheets/d/1D8BcRgEr6I-eeoG0KPUz1HrZuvvC_BDZXgeCoRuKcgg/edit?usp=sharing

**Comment by lionelB** [comment]
ok ! on regarde ca dans la semaine!

**Comment by lionelB** [comment]
la migration n'est pas passé il faudrait la modifier et supprimant les doublons
