### ISSUE TITLE
Ardennes - Suppression de doublon

### ISSUE THREAD

**Issue by JonathanRaimond** [SocialGouv/carnet-de-bord#599]
Retour de Mme. Malika E.
"Je reviens vers vous car j'ai de nouveau un doublon dans ma liste d'accompagnement. Madame Stéphanie J. est présente deux fois. La bonne est celle écrite en toutes lettres (la mauvaise a un point d'interrogation au milieu de son nom). J'ai bien invité la référente de Pôle Emploi sur le bon dossier. Le doublon peut donc bien être supprimé.

**Comment by Augustin82** [comment]
Done.
