### ISSUE TITLE
Ardennes - Problèmes pour consulter mes bénéficiaires

### ISSUE THREAD

**Issue by JonathanRaimond** [SocialGouv/carnet-de-bord#602]
Emilie S. dit ne lus voir ses bénéficiaires alors quelle pouvait consulter leur dossier hier.
Bénéficiaires concernés : Nathalie O., Jean-Claude T., Valérie Le R. et Didier M.

**Comment by Augustin82** [comment]
@JonathanRaimond je t'ai répondu hier dans le Mattermost.

> je vois toujours 23 carnets rattachés à Mme Seguinot
> elle-même est toujours correctement rattachée au CFPPA du 08
> les bénéficiaires dont elle parle dans Crisp n'existent pas dans notre base
> à part moi et Lionel, personne ne peut supprimer de gens, je pense
> vois avec Lio mais ça m'étonne qu'elle ait vu des bénéfs qui ont ensuite disparu
> ça vaut le coup de demander un peu mieux (quand c'était précisément, si elle peut)

De mon côté, donc, à moins que @lionelB n'ait fait quelque chose, je suis en attente de précisions de ta part ou de celle de notre utilisatrice.

**Comment by JonathanRaimond** [comment]
@Augustin82 je reviens vers toi suite à la réponse de Charles. Tout est normal ! Les bénéficiaires n'avaient pas encore été importés.
Ci-dessous son retour :
"Il s’agit des orientations de PE, nous sommes en train de finaliser les mises à jour en ce sens (passage d’appel à projet en marché public…).
On est raccord sur 3 des 4 noms et on en a un en plus qui n’apparait pas : Valérie LEROUX.
La coordinatrice fait le point avec la référente, je te dis ensuite, mais c’est normal, on n’avait pas encore importé ces personnes."
