### ISSUE TITLE
Page bénéficiaire: champ "ma situation" 

### ISSUE THREAD

**Issue by lkouad** [SocialGouv/carnet-de-bord#65]
liste choix multiple
__
En recherche d’emploi
En   recherche de formation
En   recherche d’alternance
En   recherche de stage
En   emploi
En   formation
En   stage
En   alternance
En   service civique
En   CDD
En   CDI
En   IAE
En   interim
En   construction de projet
En   projet entrepreneurial
Entrepreneur
Autre "ajoute info envoie   admin"

**Comment by tglatt** [comment]
see https://github.com/SocialGouv/carnet-de-bord/issues/66
