### ISSUE TITLE
Page bénéficiaire: "Mes Droits"

### ISSUE THREAD

**Issue by lkouad** [SocialGouv/carnet-de-bord#67]
Liste choix multiple
__
RQTH 
ARE
ASS
Prime d’activité 
RSA_ Droit ouvert et suspendu 
RSA_Droit ouvert et versable
RSA_Droit ouvert mais versement suspendu

**Comment by tglatt** [comment]
see https://github.com/SocialGouv/carnet-de-bord/issues/66
