### ISSUE TITLE
Créer des identifiants pour les utilisateurs ayant plusieurs comptes 

### ISSUE THREAD

**Issue by ronanjames** [SocialGouv/carnet-de-bord#671]
CD 35 
1/ jeannine : créer un identifiant pour son compte gestionnaire de structure

CD 95 
1/ Anne (mail en MP)
- créer un identifiant pour un compte responsable de cohorte 

CD 51 
1/ Franck : créer un identifiant pour son compte gestionnaire de structure 
2/ Benoit (mail en MP) : 
- créer un identifiant pour un compte accompagnateur attaché à la structure "Pôle emploi Châlons-en-Champagne"
- créer un identifiant pour un compte gestionnaire de structure attaché aux structures : Pôle emploi  Reims Bezanne, Pôle emploi  Reims Jeanne d'Arc, Pôle emploi Reims La Neuvillette, Pôle emploi Châlons-en-Champagne

**Comment by Augustin82** [comment]
- [x] Jeannine
- [ ] Anne
- [ ] Franck
- [ ] Benoît

**Comment by Augustin82** [comment]
@lionelB faut réfléchir à une manière "superadmin" de faire ça, tu penses ? Plutôt que de le gérer manuellement ?

**Comment by lkouad** [comment]
Yep moi aussi c'est bien mon impression @lionelB On en parle jeudi?
