### ISSUE TITLE
Ajouter une date de fin prévisionnelle et/ou une durée prévisionnelle à Situation actuelle

### ISSUE THREAD

**Issue by lkouad** [SocialGouv/carnet-de-bord#816]
#### Problème
Actuellement dans carnet de bord la "situation actuelle" permet de prendre connaissance de la situation du bénéficiaire au regard de l'emploi. Elle comprend uniquement la date debut et ne  permet donc pas de planifier la disponibilité ou l'indisponibilité de la personne
#### Solution
 L'utilisateur ajoute une date prévisionnelle  de fin ou une durée en fonction du type de situation et des informations dont il dispose. Cette date peut être modifié. La date et la durée  s'affiche en consultation afin de faciliter le calcul de droit ou la mise en oeuvre d'action associé
###### Les critères d'acceptation  
Étant donné que j'ai ajouté un type de situation et que j'ajoute une date début
1/ Lorsque je rentre une date de fin prévisionnelle postérieur à la date de début  et que la durée se calcul automatiquement
Alors je peux consulter sur l'écran d'accueil du bénéficiaire la date de début, la date de fin et la durée de la situation " Du xx/xx/xxxx au xx/xx/xxxx ( x mois)
![image](https://user-images.githubusercontent.com/83343517/167446536-f834cd5d-2d21-4fe5-8119-f3b825657339.png)

2/Lorsque je rentre une date de fin prévisionnelle antérieure à la date de début 
Alors le systeme affiche un message "Veuillez sélectionner une date de fin  valide"
![image](https://user-images.githubusercontent.com/83343517/167446944-45a7a5a5-c7ce-4182-bb69-723955318085.png)

3/ Lorsque je rentre une date de fin prévisionnelle postérieure à la date de début et que je souhaite changer la durée de la situation
Alors le systéme afffiche un message d'erreur "Veuillez modifier ou supprimer la date de fin prévisionnelle"
![image](https://user-images.githubusercontent.com/83343517/167447175-26f11cf2-723d-4f19-b5b3-bf8f5f6d1aed.png)

###### Les critères d'acceptation  
Étant donné que j'ai ajouté un type de situation et que j'ajoute une date début
1/ Lorsque je rentre une durée en mois 
Alors je peux consulter la date de fin prévisionnelle qui se calcul automatiquement
![image](https://user-images.githubusercontent.com/83343517/167447930-2052f747-75eb-46d7-b5d8-de4bd17c2497.png)

2/Lorsque je rentre une  durée et que je veux modifier la date de fin prévisionnelle 
Alors le systeme affiche un message "Veuillez modifier ou supprimer la durée"
![image](https://user-images.githubusercontent.com/83343517/167448094-75bfcc76-1297-441b-b040-1153cd3e58ed.png)

###### Les critères d'acceptation  
Étant donné que j'ai ajouté un type de situation et que j'ajoute une date début
1/ Lorsque je n'ajoute pas de durée ou de fin et que je valide
Alors systéme affiche depuis le sur l'écran d'accueil 
#### Besoins futures.
Cette information pourrait apparaitre dans l'historique en V1

**Comment by lkouad** [comment]
@Lotphy
-  il manque l'affichage sur le devant
Étant donné que j'ai ajouté un type de situation et que j'ajoute une date début
1/ Lorsque je rentre une date de fin prévisionnelle postérieur à la date de début et que la durée se calcul automatiquement
Alors je peux consulter sur l'écran d'accueil du bénéficiaire la date de début, la date de fin et la durée de la situation " Du xx/xx/xxxx au xx/xx/xxxx ( x mois)
![image](https://user-images.githubusercontent.com/83343517/170281091-69694766-fd1c-4d56-8052-99aa9deb386f.png)

**Comment by Lotphy** [comment]
> @Lotphy
> 
>     * il manque l'affichage sur le devant
>       Étant donné que j'ai ajouté un type de situation et que j'ajoute une date début
>       1/ Lorsque je rentre une date de fin prévisionnelle postérieur à la date de début et que la durée se calcul automatiquement
>       Alors je peux consulter sur l'écran d'accueil du bénéficiaire la date de début, la date de fin et la durée de la situation " Du xx/xx/xxxx au xx/xx/xxxx ( x mois)
>       ![image](https://user-images.githubusercontent.com/83343517/170281091-69694766-fd1c-4d56-8052-99aa9deb386f.png)

Ah oui bien vu, je rajoute ça

**Comment by lionelB** [comment]
done in https://github.com/SocialGouv/carnet-de-bord/pull/843
