### ISSUE TITLE
Date situation actuelle Modifier "au" pour "jusqu'au"

### ISSUE THREAD

**Issue by lkouad** [SocialGouv/carnet-de-bord#915]
Retour de Charles pour améliorer la compréhension
![image](https://user-images.githubusercontent.com/83343517/177392207-55e7daa7-310e-4e75-be2b-b265ee572bce.png)

**Comment by vjousse** [comment]
Implémentée dans #994

**Comment by Pauldoliveira** [comment]
@vjousse concernant celle-ci la modif apparait seulement dans le commentaire il faut aussi effectuer la modification de wording à cet endroit 
![image](https://user-images.githubusercontent.com/88043557/184833178-1be808e5-22a7-4660-b31c-b1d749d1b679.png)

**Comment by Pauldoliveira** [comment]
Nous fermons le ticket #915 en l'état (avec la modification dans le formulaire de saisie effectuée) 
Nous ouvrons un nouveau ticket pour prendre en compte le champ manquant
