### ISSUE TITLE
Ajouter une date de fin: Ajouter un raccourcis 24 mois dans les durées

### ISSUE THREAD

**Issue by lkouad** [SocialGouv/carnet-de-bord#916]
![image](https://user-images.githubusercontent.com/83343517/177394546-3088a8ec-b20d-4c7b-8d19-817d819087fb.png)

**Comment by vjousse** [comment]
Implémenté dans #993

**Comment by Pauldoliveira** [comment]
ok pour déploiement :) merci @vjousse
