### ISSUE TITLE
Ajouter un date picker sur les champs de date

### ISSUE THREAD

**Issue by JonathanRaimond** [SocialGouv/carnet-de-bord#921]
Actuellement les champs pour saisir une date présentent une icône calendrier mais cette dernière n'est pas reliée à un date picker.
![Capture d’écran 2022-07-07 à 10 39 30](https://user-images.githubusercontent.com/85908681/177730688-ddef7352-b123-44c1-8898-17272d544fdb.png)

**Comment by lionelB** [comment]
testé sur chrome et firefox; c'est ok !
