### ISSUE TITLE
ETQ gestionnaire de structure, ajouter un co-gestionnaire de structure

### ISSUE THREAD

**Issue by lkouad** [SocialGouv/carnet-de-bord#957]
### Discussed in https://github.com/SocialGouv/carnet-de-bord/discussions/855

**Problème**

Les interlocuteurs demandent pour des raisons techniques, métiers ou "politiques", la création de plusieurs profils gestionnaires de structure. Or, lorsque le déploiement est déjà créé, il n'est pas possible depuis une interface gestionnaire de structure de rajouter un gestionnaire de structure. 

**Solution :**

Permettre au gestionnaire de structure d'ajouter un co-gestionnaire de structure (encadré vert sur la maquette)

Les critères d'acceptation :
Étant donné que je dispose d'un accès gestionnaire de structure 
Lorsque je clique sur "Ajouter un gestionnaire" 
J'accède à un volet latéral de création où je dois indiquer Nom Prénom Adresse mail du nouveau gestionnaire que je souhaite ajouter à ma structure (cf. deuxième maquette). 

**Maquette**

<img width="1122" alt="173396989-49526961-aad1-4d24-9a34-75d18dbc3718" src="https://user-images.githubusercontent.com/79253400/186004051-abe3b69d-4f48-4dc5-af60-45da972d4da3.png">
<img width="1441" alt="Capture d’écran 2022-08-24 à 11 08 50" src="https://user-images.githubusercontent.com/79253400/186379861-f97d219a-60b3-4ae9-888d-728fa7c3e9ff.png">

**Comment by lionelB** [comment]
Il y a une imprécision concernant la rédaction de l'épic... on parle d'un problème coté admin cdb et la solution proposée repose sur une implémentation coté admin de structure. Je trouve étrange qu'un admin de structure puisse modifier les infos d'autres admin de structure et surtout les supprimer. cela devrait être fait par le manager ou l'admin cdb selon moi.
