### ISSUE TITLE
Analyse donnée PE

### ISSUE THREAD

**Issue by JonathanRaimond** [SocialGouv/carnet-de-bord#967]

**Comment by lionelB** [comment]
l'analyse de l'import a donnée lieux à plusieurs PR
- Problème de format dans la colonne BRSA (on attendait un O / N  or les valeurs dans le fichier etaient OUI / NON
- Erreur d'exécution en fin de script (pb d'asyncio. On attend bien la fin et la fermeture des connexion avant de rendre la main)
