### ISSUE TITLE
Debug Script PE

### ISSUE THREAD

**Issue by JonathanRaimond** [SocialGouv/carnet-de-bord#968]

**Comment by vjousse** [comment]
Première mise en production du script PE effectuée hier :+1:

**Comment by lionelB** [comment]
Suite au mob programing, nous avons pu régler les pb suivant
- Ajout des clés d'api manquante pour la connexion aux api PE (récupération des agences)
- Erreur d'exécution en fin de script (pb d'asyncio. On attend bien la fin et la fermeture des connexion avant de rendre la main)
- identification d'un bug sur l'insertion des pro dans le groupe de suivi - [#972]
- identification d'un piste d'amélioration du script - [#973]
