### ISSUE TITLE
PE - Inserer le pro dans notebook_member si le pro existe deja

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/carnet-de-bord#972]
Actuellement, si le pro est présent dans notre base, on ne l'ajoute pas en base mais on ne l'ajoute pas non plus dans le groupe de suivis. Il faudrait dans le cas ou le pro existe déjà, l'ajouter dans le groupe de suivi.
Suite au dernier import; il faut aussi prévoir un script pour insérer les pro manquants dans les groupe de suivi

**Comment by vjousse** [comment]
Mergé dans #974
