### ISSUE TITLE
Modifier le wording date "au" par "jusqu'au" dans la section "situation socioprofessionnelle" d'un carnet de bord 

### ISSUE THREAD

**Issue by Pauldoliveira** [SocialGouv/carnet-de-bord#997]
### Problème

Charles, le chargé de déploiement des Ardennes, à proposé de remplacer le mot "au" par "jusqu'au" pour l'affichage de la date correspondant à la situation socioprofessionnelle.
![image](https://user-images.githubusercontent.com/88043557/184853848-cdb4ef94-9bd7-44e3-8525-94d155605e5a.png)

### Solution

Remplacer le mot.

### Test

ETQ professionnel connecté à Carnet de bord ( pierre.chevalier )
QUAND je consulte le carnet de bord d'un de mes bénéficiaires
ET QUE je consulte la section "situation socioprofessionnelle"
ALORS la date de la situation actuelle s'affiche de la façon suivante (exemple) : 
>**En IAE** du XX/XX/XXXX jusqu'au XX/XX/XXXX - **(environ X [jours, mois, ans])**

**Comment by Pauldoliveira** [comment]
changement de wording complémentaire:
- Dans l'item "situation sociopro" remplacé en ... **du** par "en ... **depuis le** 
- Dans l'item "plan d'action" remplacé "du XX/XX/XXXX au XX/XX/XXXX" par "depuis le XX/XX/XXXX jusqu'au XX/XX/XXXX"

**Comment by lionelB** [comment]
fix by  #1001
